### ISSUE TITLE
devDependencies are removed but not the resolutions for these dependencies

### ISSUE THREAD

**Issue by sanderdejong88** [mdasberg/grunt-release-me#8]
The devDependencies from bower.json are removed. When I have a few resolutions for these dependencies these should also be removed from the resolutions property.

**Comment by quachc** [comment]
Shouldn't we completely remove resolutions, it's there to resolve conflicts but it should be specified by the 'user' of the plugin.
It's really strange to me to let a dependency of a project specify which version of another dependency should be used...

**Comment by mdasberg** [comment]
I agee with Chris, this should be something the user provides.

**Comment by sanderdejong88** [comment]
I also agree. We should completly remove resolutions.
